version: "3.8"

services:
    bot-service:
        env_file: .env
        container_name: bot
        hostname: bot
        build:
          context: bot-service
        ports:
            - "${BOT_PORT}:${BOT_PORT}"
        command: npm run start:prod
        environment:
            - ${BOT_TOKEN}
            - ${POSTGRES_PASSWORD}
            - ${POSTGRES_USER}
            - ${POSTGRES_HOST}
            - ${POSTGRES_DATABASE}
        restart: always
        healthcheck:
            test: ["CMD", "curl", "--fail", "http://localhost:3000/ping"]
            interval: 5s
            timeout: 5s
            retries: 3

    frontend:
        env_file: .env
        container_name: frontend
        build:
            context: frontend
                - 81:80
        command: npm run build
        environment:
            - ${API_HOST}
        restart: always