version: "3.8"

services:
    bot-service:
        command: npm run start:dev
        volumes:
            - ./bot-service:/usr/src/app
            - /usr/src/app/node_modules

    ml-service:
        command: npm run start:dev
        volumes:
            - ./ml-service:/usr/src/app
            - /usr/src/app/node_modules

    frontend:
        build:
            target: base
        ports:
            - 4000:4000
        command: npm run start
        restart: always
        volumes:
            - ./frontend:/usr/src/app
            - /usr/src/app/node_modules