version: "3.8"

services:
    bot-service:
        command: npm run start:dev
        volumes:
            - ./bot-service:/usr/src/app
            - /usr/src/app/node_modules

    ml-service:
        command: npm run start:dev
        volumes:
            - ./ml-service:/usr/src/app
            - /usr/src/app/node_modules

    frontend:
        build:
            target: base
        ports:
            - 4000:4000
            - 80:80
        command: npm run start
        environment:
            - ${API_HOST}
        restart: always
        volumes:
            - ./frontend:/usr/src/app
            - /usr/src/app/node_modules